/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/Sidebar`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/TypingIndicator`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/AnimatedLogo`; params?: Router.UnknownInputParams; } | { pathname: `/../src/stores/suggestedPrompt`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/SkillsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/skills` | `/skills`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/memory` | `/memory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sessions` | `/sessions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/Sidebar`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/TypingIndicator`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/AnimatedLogo`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/stores/suggestedPrompt`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/screens/SkillsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/skills` | `/skills`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/memory` | `/memory`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sessions` | `/sessions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/onboarding${`?${string}` | `#${string}` | ''}` | `/../src/components/Sidebar${`?${string}` | `#${string}` | ''}` | `/../src/components/TypingIndicator${`?${string}` | `#${string}` | ''}` | `/../src/components/AnimatedLogo${`?${string}` | `#${string}` | ''}` | `/../src/stores/suggestedPrompt${`?${string}` | `#${string}` | ''}` | `/../src/screens/SkillsScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/skills${`?${string}` | `#${string}` | ''}` | `/skills${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/memory${`?${string}` | `#${string}` | ''}` | `/memory${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sessions${`?${string}` | `#${string}` | ''}` | `/sessions${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/Sidebar`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/TypingIndicator`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/AnimatedLogo`; params?: Router.UnknownInputParams; } | { pathname: `/../src/stores/suggestedPrompt`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/SkillsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/skills` | `/skills`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/memory` | `/memory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sessions` | `/sessions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
